In [1]:
import numpy as np

In [2]:
import array

In [6]:
# creating an array
ary = np.array([1,2,3,4,5])
print(ary)
print(type(ary))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# here the integer type data gets upcasted to string type
np.array([2, 4, 6, 8, 'Even'])

array(['2', '4', '6', '8', 'Even'], dtype='<U21')

In [8]:
# float and int gets upcasted to string
np.array([2.0, 4, 6, 8.2, 'Even'])

array(['2.0', '4', '6', '8.2', 'Even'], dtype='<U32')

In [9]:
# creating a 1D array
np.array([1, 2, 3])

array([1, 2, 3])

In [10]:
# 2D array
np.array([[1,2,3], [4,5,6]])    #numbers can be given in the form of list or tuple the output will be same

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# 3D array
np.array([[[1,2],[3,4]], [[6,7],[8,9]]])

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [19]:
# creating nD array by specifing the ndim 
np.array([2,3,4,5,6,7,8], ndmin = 3)

array([[[2, 3, 4, 5, 6, 7, 8]]])

In [18]:
np.array([[1,2], [3,4], [5,6,7]]) #third element is not of the same order 

<ipython-input-18-a33ef3418dc1>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2], [3,4], [5,6,7]])


array([list([1, 2]), list([3, 4]), list([5, 6, 7])], dtype=object)

In [20]:
# convert the data type into complex
np.array([1,3,5,7], dtype = complex)

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j])

In [28]:
# changing the dtype of the array components

arr = np.array([(1,2), (3,4)], dtype = [('a', '<i2'),('b', '<i8')])

In [29]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [30]:
type(arr[1][0])

numpy.int16

In [31]:
type(arr[1][1])

numpy.int64

In [32]:
arr = np.array([(1,2), (3,4), (5,6)], dtype = [('a', '<i2'),('b', '<i8')])

In [36]:
type(arr[2][0])

numpy.int16

In [42]:
# numpy matrix
arr1 = np.array([[1,2,3], [4,5,6]])
np.mat(arr1)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [43]:
# convert list into an array
# 1
l = [2,4,6,8,10]

np.array(l)

array([ 2,  4,  6,  8, 10])

In [45]:
# 2
np.asarray(l)

array([ 2,  4,  6,  8, 10])

In [46]:
# 3 
np.asanyarray(l)

array([ 2,  4,  6,  8, 10])

In [49]:
mat = np.mat(l) # first converting the list into a matrix
np.asanyarray(mat)    # matrix is already a sub-array, so asanyarray doesnt convert it

matrix([[ 2,  4,  6,  8, 10]])

In [50]:
np.asarray(mat)

array([[ 2,  4,  6,  8, 10]])

In [51]:
# checking if matrix is a subclass of array
issubclass(np.matrix, np.ndarray)

True

In [52]:
# checking if ndarray is a subclass of matrix
issubclass(np.ndarray, np.matrix)

False

In [53]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# deep copy vs Shallow copy

a = arr1    # shallow copy
b = np.copy(arr1)    # deep copy

In [56]:
arr1[0][0] = 77    # changing the first element of arr1, array is a mutable datatype

In [57]:
a   # since a points to the same location as that of arr1

array([[77,  2,  3],
       [ 4,  5,  6]])

In [58]:
b    # a new location is created where the value of b is stored

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
for i in arr1:
    print(i)

[77  2  3]
[4 5 6]


In [60]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
np.fromfunction(lambda i, j: i**2, (4,4))

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [4., 4., 4., 4.],
       [9., 9., 9., 9.]])

In [65]:
np.fromfunction(lambda i, j: i/j, (3,3))  # inf is a floationg point representation of positive infinity in numpy

<ipython-input-65-cc1ffa8191d2>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j: i/j, (3,3))
<ipython-input-65-cc1ffa8191d2>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j: i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [66]:
gen = (i*i for i in range(5))

In [67]:
gen

<generator object <genexpr> at 0x7fa832bc7040>

In [69]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [70]:
np.fromiter(range(6), dtype = int)    # since range is also a generator function

array([0, 1, 2, 3, 4, 5])

In [71]:
# convert string to array
np.fromstring('1,2,3,4', sep = ',', dtype = int)

array([1, 2, 3, 4])

In [81]:
np.fromstring('222 333 444 555', sep = ' ', dtype = int)

array([222, 333, 444, 555])

In [82]:
arr1.size    # no.of elements present inside the array

6

In [84]:
arr1.shape

(2, 3)

In [85]:
# creating a 3D array

arr2 = np.array([[[1,2,3,4], [2,3,4,5]],[[1,2,3,4], [2,3,4,5]]])

In [86]:
arr2

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [88]:
arr2.shape    # there are two array of 2X4 dimension

(2, 2, 4)

In [87]:
arr2.ndim

3

In [90]:
list(range(5))

[0, 1, 2, 3, 4]

In [91]:
list(range(4.5))   # range doesnt take float argument

TypeError: 'float' object cannot be interpreted as an integer

In [89]:
np.arange(4.8)    # numpy arange takes float argument, it is a substitute of range 

array([0., 1., 2., 3., 4.])

In [92]:
np.arange(4.8, 8.8, 0.2)

array([4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2,
       7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8])

In [93]:
np.arange(9, 6.6, -0.3)    # np.arange takes the upper bound when the arguments are float type

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [95]:
np.arange(1,10,2)    # for int type argument upper bound is excluded

array([1, 3, 5, 7, 9])

In [97]:
# numpy linspace
np.linspace(5,6,10)   # start, stop, no.of data points

array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [98]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [99]:
np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [100]:
np.ones(4)

array([1., 1., 1., 1.])

In [102]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [103]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [104]:
np.empty((2,3,4))

array([[[1.84963079e-316, 0.00000000e+000, 6.93476163e-310,
         6.93476163e-310],
        [6.93476163e-310, 6.93476163e-310, 6.93476163e-310,
         6.93476163e-310],
        [6.93476163e-310, 6.93476163e-310, 6.93476163e-310,
         6.93476163e-310]],

       [[6.93476163e-310, 6.93476163e-310, 6.93476163e-310,
         6.93476163e-310],
        [6.93476163e-310, 6.93476163e-310, 6.93476163e-310,
         6.93476163e-310],
        [6.93476163e-310, 6.93476163e-310, 6.93476163e-310,
         6.93476163e-310]]])

In [105]:
np.eye(3)    # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.linspace([1,4],2, endpoint = False, axis = 1)

array([[1.  , 1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 ,
        1.22, 1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42,
        1.44, 1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64,
        1.66, 1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86,
        1.88, 1.9 , 1.92, 1.94, 1.96, 1.98],
       [4.  , 3.96, 3.92, 3.88, 3.84, 3.8 , 3.76, 3.72, 3.68, 3.64, 3.6 ,
        3.56, 3.52, 3.48, 3.44, 3.4 , 3.36, 3.32, 3.28, 3.24, 3.2 , 3.16,
        3.12, 3.08, 3.04, 3.  , 2.96, 2.92, 2.88, 2.84, 2.8 , 2.76, 2.72,
        2.68, 2.64, 2.6 , 2.56, 2.52, 2.48, 2.44, 2.4 , 2.36, 2.32, 2.28,
        2.24, 2.2 , 2.16, 2.12, 2.08, 2.04]])

In [107]:
np.logspace(2, 3, 4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [109]:
d = np.linspace(4,8,40)

In [110]:
d

array([4.        , 4.1025641 , 4.20512821, 4.30769231, 4.41025641,
       4.51282051, 4.61538462, 4.71794872, 4.82051282, 4.92307692,
       5.02564103, 5.12820513, 5.23076923, 5.33333333, 5.43589744,
       5.53846154, 5.64102564, 5.74358974, 5.84615385, 5.94871795,
       6.05128205, 6.15384615, 6.25641026, 6.35897436, 6.46153846,
       6.56410256, 6.66666667, 6.76923077, 6.87179487, 6.97435897,
       7.07692308, 7.17948718, 7.28205128, 7.38461538, 7.48717949,
       7.58974359, 7.69230769, 7.79487179, 7.8974359 , 8.        ])

In [111]:
d.shape

(40,)

In [112]:
d.ndim

1

In [114]:
d.reshape(20,2)

array([[4.        , 4.1025641 ],
       [4.20512821, 4.30769231],
       [4.41025641, 4.51282051],
       [4.61538462, 4.71794872],
       [4.82051282, 4.92307692],
       [5.02564103, 5.12820513],
       [5.23076923, 5.33333333],
       [5.43589744, 5.53846154],
       [5.64102564, 5.74358974],
       [5.84615385, 5.94871795],
       [6.05128205, 6.15384615],
       [6.25641026, 6.35897436],
       [6.46153846, 6.56410256],
       [6.66666667, 6.76923077],
       [6.87179487, 6.97435897],
       [7.07692308, 7.17948718],
       [7.28205128, 7.38461538],
       [7.48717949, 7.58974359],
       [7.69230769, 7.79487179],
       [7.8974359 , 8.        ]])

In [117]:
d.reshape((2,2,10))

array([[[4.        , 4.1025641 , 4.20512821, 4.30769231, 4.41025641,
         4.51282051, 4.61538462, 4.71794872, 4.82051282, 4.92307692],
        [5.02564103, 5.12820513, 5.23076923, 5.33333333, 5.43589744,
         5.53846154, 5.64102564, 5.74358974, 5.84615385, 5.94871795]],

       [[6.05128205, 6.15384615, 6.25641026, 6.35897436, 6.46153846,
         6.56410256, 6.66666667, 6.76923077, 6.87179487, 6.97435897],
        [7.07692308, 7.17948718, 7.28205128, 7.38461538, 7.48717949,
         7.58974359, 7.69230769, 7.79487179, 7.8974359 , 8.        ]]])

In [121]:
# generating random numbers
# follows uniform distribution

np.random.rand(5)

array([0.71865756, 0.18002006, 0.23811735, 0.65235205, 0.71757377])

In [122]:
# follows standard normal distribution.
np.random.randn(5)

array([-0.31942957,  0.65822239, -0.97132901, -0.93764602, -1.16679631])

In [123]:
np.random.randn(3,4)

array([[ 1.84988841, -0.39378574, -0.96725624,  0.36414418],
       [-0.39872597,  0.09502162, -0.248507  ,  1.02209775],
       [-1.98968869,  2.06464267, -0.65235963, -0.56791446]])

In [125]:
np.random.randn(2,3,4)

array([[[ 1.62656983,  0.29737716,  1.53103927, -0.2047716 ],
        [ 0.27737116, -0.26172118, -1.34808624, -0.23782905],
        [ 0.42207564,  0.24538546, -0.70966572,  0.36221937]],

       [[ 0.14091408, -0.80576549, -0.10059371,  2.09961652],
        [ 1.08351907,  1.33922658,  0.4689647 ,  0.43135572],
        [-0.41599701,  2.02328247, -1.40001095, -0.49725604]]])

In [127]:
# generate random integer number

np.random.randint(50)

25

In [130]:
np.random.randint(2,54,(4,4))    # create a 4X4 matrix where the elements will be random no.s between 2 and 54

array([[43, 42, 39, 42],
       [30, 49, 18, 21],
       [44, 48, 16, 44],
       [24, 26, 17,  9]])

In [131]:
arr = np.random.randint(3,9,(3,3))

In [132]:
arr

array([[6, 8, 7],
       [4, 4, 8],
       [7, 4, 5]])

In [133]:
arr.reshape(9,1)

array([[6],
       [8],
       [7],
       [4],
       [4],
       [8],
       [7],
       [4],
       [5]])

In [134]:
arr.reshape(1,1,9)

array([[[6, 8, 7, 4, 4, 8, 7, 4, 5]]])

In [135]:
arr.reshape(3,3,1)

array([[[6],
        [8],
        [7]],

       [[4],
        [4],
        [8]],

       [[7],
        [4],
        [5]]])

In [136]:
arr.reshape(1, -22)    # numpy takes the first argument(1) and guessess the unknown dimension
                       # Pass -1 (can be any negative number) as the value, and NumPy will calculate this number for you.

array([[6, 8, 7, 4, 4, 8, 7, 4, 5]])

In [139]:
arr1

array([[77,  2,  3],
       [ 4,  5,  6]])

In [138]:
arr1.max()

77

In [150]:
arr3 = np.random.randint(4,50, (5,5))

In [151]:
arr3

array([[20, 29, 43, 35, 48],
       [33, 39, 44, 16, 16],
       [47, 15, 20, 15, 40],
       [11, 15, 14, 26, 11],
       [48, 39, 32, 24, 24]])

In [142]:
arr3[3: , 3: ]

array([[45, 19],
       [23, 29]])

In [143]:
arr3[0:2, 1:3]

array([[15, 41],
       [20, 44]])

In [146]:
arr3[:, [1,3]]   # select all the rows and 1st and 3rd column

array([[15,  6],
       [20, 26],
       [25, 43],
       [23, 45],
       [11, 23]])

In [147]:
arr3>20

array([[ True, False,  True, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True, False,  True,  True,  True]])

In [153]:
arr11 = np.random.randint(2,4, (2,2))
arr22 = np.random.randint(2,4, (2,2))

In [154]:
arr11

array([[3, 3],
       [2, 3]])

In [155]:
arr22

array([[3, 2],
       [2, 2]])

In [156]:
# Element wise multiplication
arr11*arr22

array([[9, 6],
       [4, 6]])

In [157]:
# Matrix multiplication

arr11@arr22

array([[15, 12],
       [12, 10]])

In [158]:
# element wise operation
 
arr11**2

array([[9, 9],
       [4, 9]])

In [164]:
# Broadcasting (row wise)

arr5 = np.zeros((3,4))

In [165]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [166]:
arr5 +3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [167]:
arr6 = [1,2,3,4]
arr5+arr6

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [171]:
# Broadcasting (column wise)

arr12 = np.random.randint(2,6, 3)

In [172]:
arr12

array([5, 3, 5])

In [173]:
arr12_new = arr12.reshape((3,1))

In [174]:
arr12_new

array([[5],
       [3],
       [5]])

In [175]:
arr5 + arr12_new

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [178]:
np.random.seed(42)
np.random.rand(2,4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])